demoapp:
  build: .
  ports:
   - "3000:3000"
  environment:
    REDIS_PORT: 6379
  labels:
    HTTP_ROUTE: true
    DOMAINS: demo1.cloudray.net
  links:
    - redis

redis:
  image: redis:3.0.1
  ports:
   - "6379:6379"
